# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y0qOcVMoWkIGp01G7Cit4rUqTlw3LWrl
"""

#Họ và tên: Võ Văn Trường
#MSSV: 18119206
#Lớp: Chiều thứ 4 tiết 7-9

import numpy as np
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation
import tensorflow as tf
import matplotlib.pyplot as plt
import datetime as dt

mnist = tf.keras.datasets.mnist
(X_train, y_train) , (X_test, y_test) = mnist.load_data() 
X_train = np.reshape(X_train,(60000,784))/255.0
X_test = np.reshape(X_test,(10000,784))/255.0
y_train= np_utils.to_categorical(y_train,10)
y_test= np_utils.to_categorical(y_test,10)

model = Sequential()
model.add(Dense(1024,input_dim = 784, activation= 'sigmoid'))
model.add(Dense(512,input_dim = 1024, activation= 'sigmoid'))
model.add(Dense(10, activation= 'softmax'))
model.compile(loss = 'binary_crossentropy', optimizer='sgd', metrics= ["accuracy"])

model.fit(X_train, y_train, batch_size= 100, epochs= 10, validation_data=(X_test, y_test), verbose= 1)

score = model.evaluate (X_test, y_test, batch_size= 128)

X_train.shape


#add comment abcccc